---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348 Fall 2019"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
```

# Modeling

## Instructions

A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 11/24/2019. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)! 

Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).

## Find data:

Find one dataset with at least 5 variables that wish to use to build model. At least one should be categorical (with 2-5 groups) and at least two should be numeric. Ideally, one of your variables will be binary (if not, you will need to create one by discretizing a numeric, which is workable but less than ideal). You will need a minimum of 40 observations (*at least* 10 observations for every explanatory variable you have, ideally 20+ observations/variable).

It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, you could also diversify your portfolio a bit by choosing a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.

Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: https://vincentarelbundock.github.io/Rdatasets/datasets.html.


## Guidelines and Rubrc

- **0. (5 pts)** Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph.
```{R}
ICU<-read_csv("ICU.csv")
view(ICU)

```
This Intensive Care Unit Patients dataset includes data from a sample of 200 pateints at an ICU. There are 9 varibles presents : patient ID code, patient survial, age, age group, sex, infection suspected, systolic blood pressure, heart rate, and status of admission.

- **1. (15 pts)** Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).

```{R}
#MANOVA
manova<-manova(cbind(Age,SysBP,Pulse)~Survive, data=ICU)
summary(manova)


#univariate ANOVA
library(mvtnorm)
ICU%>%group_by(Survive)%>%summarize(mean(Age),mean(SysBP),mean(Pulse))
ICU$Survive <-factor(ICU$Survive)
summary.aov(manova)

#post hoc
pairwise.t.test(ICU$Age,ICU$Survive,p.adj="none")
pairwise.t.test(ICU$SysBP,ICU$Survive,p.adj="none")


#type 1 error
#number of tests = 1 MANOVA, 3 ANOVA, 2 t tests
type1error=1-(1-0.05)^6
type1error


#Boneforroni
Boneforroni=(0.05)/6
Boneforroni

#adjusted
pairwise.t.test(ICU$Age,ICU$Survive,p.adj="bonf")
pairwise.t.test(ICU$SysBP,ICU$Survive,p.adj="bonf")


```
A MANOVA was conducted to determine the effect of age, systolic blood pressure, and heart rate on survial. The p-value of 0.0008221 is lower than the alpha value of 0.05. We reject the null hypothesis and conclude that at least one of these variables, the means are different. Since this is significant, I continued with running a univariate ANOVA to see which variables are significant and post-hoc-t-test to see which ones differed.

Based on the ANOVA, we see that the means of at least one reponse varibale differs. The p-value is 0.0072 for test with age and 0.0036 for the test with systolic blood pressure. These are both less than the alpha value of 0.05 so we reject the null hypothesis and continue with running 2 post-hoc-t-tests. For blood pressure, the p-value of 0.6553 is greater than 0.05 so we fail to reject the null hypothesis. We can conclude that for blood pressurem, the means of each group are about equal.

There were 6 hypothesis tests ran (1 MANOVA, 3 ANOVA, 2 post-hoc-t-tests). The calculated overall type 1 error rate was 0.2649081.
The boneferroni adjusted significance level was calculated by 0.05/6 to be 0.008333333.

For tests of ANOVA, we assume random sample and independent observations. This are likely to be met because they are a random sample of 200 patients from a larger study.
There are also many assumptions for running MANOVA/ANOVA test. Both assume dependent variable have multivariate normality,homogeneity of within-group covariance matricies, and no extreme outliers.






- **2. (10 pts)** Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).

```{R}

#Two Sample t-test
ICU%>%group_by(Survive)%>%summarize(`mean BP`=mean(SysBP),sd=sd(SysBP),n=n())

t.test(data=ICU, SysBP~Survive, var.eq=T)


#plot
hist(ICU$SysBP, main="Histogram for Systolic Blood Pressure", 
     xlab="Systolic Blood Pressure", 
     col="light green",
     xlim=c(30,260),
     las=1, 
     breaks=20)

```
The null hypothesis for the 2 sample t-test states that the mean systolic blood pressure between the 2 groups, survived and not survived, are equal.
The alternative hypothesis for the 2 sample t-test states that the mean systolic blood pressure between the 2 groups are not equal.
I ran a 2 sample t-test and found that the p-value is 0.003647 which is lower than the alpha p-value of 0.05. We reject the null hypothesis and conclude that the mean systolic blood pressure between those who survived and those who did not survive were not equal.

- **3. (35 pts)** Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.

    - Interpret the coefficient estimates (do not discuss significance) (10)
    - Plot the regression using `ggplot()`. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (7)
    - Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (3)
    - Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (7)
    - What proportion of the variation in the outcome does your model explain? (3)
    - Finally, rerun the regression but without interactions (just main effects); compare this with the interaction model and the null model using a likelihood ratio test (4)

```{R}
library(lmtest)

#Interpret the coefficient estimates
fit1<-lm(SysBP~Age*Survive,data = ICU)
summary(fit1)

#Regression plot
ICU2<-ICU%>%mutate(y=ifelse(Survive == "Yes","1","0"))
fit5<-glm(Survive~Age, family = "binomial", data=ICU2)
coeftest(fit5) 

ICU$prob<-predict(fit5,type="response")
ICU$Survive<-as.factor(ICU$Survive)
ggplot(ICU,aes(Age,prob))+geom_point(aes(color=Survive),alpha=0.5,size=2)

#plot - assumption of normality
library(tidyverse)
library(ggplot2)
ICU$Survive<-factor(ICU$Survive,labels=c("Yes", "No"))
ICU$Sex<-factor(ICU$Sex,labels=c("F","M"))
ICU%>%ggplot(aes(Age,SysBP))+geom_point()+geom_smooth(method='lm',se=F)

#regression using heteroskedasticity robust standard errors
library(sandwich)
coeftest(fit1,vcov=vcovHC(fit1))




#rerun the regression but without interactions
fit<-lm(Age~SysBP,data = ICU)
coef(fit)
cov(ICU$SysBP,ICU$Age)/var(ICU$SysBP)
#SS total
SST<-sum((ICU$Age-mean(ICU$Age))^2)
#SS Regression
SSR<-sum((fit1$fitted.values-mean(ICU$Age))^2)
#SS Error
SSE<-sum(fit1$residuals^2)
#SSR/SST is the proportion of the total variation in y not explained
SSR/SST

#R squared
#What proportion of the variation in the outcome does your model explain? 
summary(fit1)$r.sq


```
The intercept 149.9895 is the average systolic blood pressure of the recorded 200 patients in the ICU when there is no interaction with age or survival.
The intercept -0.4785 for age indicates that for every 1 year increase in age, there is a decrease of 0.4785 mmHg in systolic blood pressure.
The intercept -27.6594 indicates that those patients who did not survive had a systolic pressure 27.6594 lower than those who did survive.
The Age:SurviveNo coefficient 0.7178 means that the average systolic blood pressure will increase after including the intereaction between surviving and increasing age.

When running the regression using heteroskedasticity robust standard errors, the p-value 0.475 was calculated. This is greater than the alpha value of 0.05 so we fail to reject the null hypothesis. This p-value is increased from the one calucluated for the regression results earlier which was 0.009129.

Based on the data calculated to find R squared, this model explains about 0.07092227 of the variation in the outcome.



- **4. (5 pts)** Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)
```{R}


#rerun the regression but without interactions
fit<-lm(Age~SysBP,data = ICU)
coef(fit)
summary(fit)

#Rerun same regression model this time compute bootstrapped standard errors
ICU_dat<-ICU[sample(nrow(ICU),replace=TRUE),]
library(lmtest)

samp_distn<-replicate(5000, {
 ICU_boot<-ICU[sample(nrow(ICU),replace=TRUE),]
 fit3<-lm(Age~SysBP,data=ICU_boot)
 coef(fit3)

})

#summary(fit3)
samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)
```

The regression model from previous calculated a p-value of 0.549 and SE of 0.04321.
The regression model after computing bootstrapped standard errors calculated a p-value of 0.776 and SE of 0.04324.

- **5. (40 pts)** Perform a logistic regression predicting a binary categorical variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary). 

    - Interpret coefficient estimates in context (10)
    - Report a confusion matrix for your logistic regression (2)
    - Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)
    - Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)
    - Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)
    - Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)
    ```{R}
#coefficient estimates
fit9<-lm(SysBP~Survive,data=ICU)
summary(fit9)

#confusion matrix
table(truth=ICU$Survive, prediction=ICU$Sex)
  
#Accuracy
(24+60)/200

#Sensitivity TPR
16/40

#Specificity TNR
100/160

#Precision PPV recall
16/76

#Density of log-odds
library(dplyr)
library(MASS)
library(ggplot2)
library(tidyverse)
library(lmtest)
ICU$odds<-(ICU$prob)/(1-ICU$prob)
ICU$logit<-(ICU$odds)
ggplot(ICU)+geom_density(aes(logit,fill= Survive),alpha=0.3)

#ROC Plot
prob<-predict(fit,type="response")
library(plotROC)
ROC<-ggplot(ICU)+geom_roc(aes(d=Survive,m=prob),n.cuts=0)
ROC

#AUC
calc_auc(ROC)

#Class diagnositcs
class_diag<-function(probs,truth){
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,auc)}


#10-fold CV
set.seed(1234)
k=10
data1<-ICU[sample(nrow(ICU)),]
folds<-cut(seq(1:nrow(ICU)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
  train<-data1[folds!=i,]
  test<-data1[folds==i,]
  truth<-test$Survive
  fit<-glm(Survive~Age+SysBP,data=train,family="binomial")
  probs<-predict(fit,newdata = test,type="response")
diags<-rbind(diags,class_diag(probs,truth))
}

apply(diags,2,mean)
```
The coefficeint estimate for systolic blood pressure is 16.819. The p-value is 0.00365 which is lower than the alpha level of 0.05. There is a significant effect of systolic blood pressure on those grouped by survival. On average, those individuals who did not survive had a systolic blood pressure 16.819 mmHg higher than those who did survive.

The AUC area under curve is calculated to be 0.3700781. This AUC is relatively poor meaning that systolic blood pressure and age are poor predictors of survival.

The 10-fold CV average out of sample accuracy is 0.8227273. The sensitivity is 0.9952153, the specificity is 0.1318182 and the recall PPV percision is 0.8248804. The AUC here is 0.6538223 which is still relatively poor meaning that systolic blood pressure and age are poor predictors of survival. But it is greater than the previous AUC of 0.3700781 which means there is no sign of overfitting.

- **6. (10 pts)** Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model's out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!
```{R}




#LASSO
install.packages("glmnet")
library(glmnet)
y<-as.matrix(ICU$Survive)
x<-model.matrix(fit1)
x


x<-x[,-1]
cv <- cv.glmnet(x, y, family = "binomial")
lasso <- glmnet(x, y, family = "binomial", lambda = cv$lambda.1se)
coef(lasso)


#10 fold CV
set.seed(1234)
k=10
data1<-ICU[sample(nrow(ICU)),]
folds<-cut(seq(1:nrow(ICU)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
  train<-data1[folds!=i,]
  test<-data1[folds==i,]
  truth<-test$Survive
  fit<-glm(Survive~Age+SysBP,data=train,family="binomial")
  probs<-predict(fit,newdata = test,type="response")
diags<-rbind(diags,class_diag(probs,truth))
}

apply(diags,2,mean)



```


## Where do I find data again?

You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.

If you are totally clueless and have no direction at all, log into the server and type 

```{R eval=F}
data(package = .packages(all.available = TRUE))
```

This will print out a list of **ALL datasets in ALL packages** installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run `data()` to bring up the datasets in your current environment. To read more about a dataset, do `?packagename::datasetname`. 

If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: https://vincentarelbundock.github.io/Rdatasets/datasets.html.

- A good package to download for fun/relevant data is `fivethiryeight`. 
Run `install.packages("fivethirtyeight"),` load the packages with `library(fivethirtyeight)`, run `data()`, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.

- If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above

- However, you *emphatically DO NOT* have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to  merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: https://www.wunderground.com/history/). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!

- Here is a curated list of interesting datasets (read-only spreadsheet format): https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit

- Here is another great compilation of datasets: https://github.com/rfordatascience/tidytuesday

- Here is the UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/index.php

    - See also https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data

- Here is another good general place to look: https://www.kaggle.com/datasets

- To help narrow your search down or to see interesting variable ideas, check out https://www.tylervigen.com/spurious-correlations. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!

- If you are interested in medical data, check out www.countyhealthrankings.org

- If you are interested in scraping UT data, they make *loads* of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: https://reports.utexas.edu/statistical-handbook

##### Broader data sources:

[Data.gov](www.data.gov) 186,000+ datasets!

[Social Explorer](Social Explorer) is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.

[U.S. Bureau of Labor Statistics](www.bls.gov)

[U.S. Census Bureau](www.census.gov)

[Gapminder](www.gapminder.org/data), data about the world.

...





